---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 736131959383052288-Og5eVtNehVlsDT6hVtRaskoTwmO0Zsa
:access_token_secret: XCAqm2XYjxhWcVDIF7CqgnvhS59rxyrObjeBkEqzz4QTp
